# Generated by Django 5.1.2 on 2024-12-04 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FireExtinguisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "fire_extinguisher_type",
                    models.CharField(
                        choices=[
                            ("Water", "Water"),
                            ("Water Mist", "Water Mist"),
                            ("Foam", "Foam"),
                            ("CO2", "CO2"),
                            ("Powder", "Powder"),
                            ("Wet Chemical", "Wet Chemical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fire_class",
                    models.CharField(
                        choices=[
                            ("Class A", "Class A"),
                            ("Class B", "Class B"),
                            ("Class C", "Class C"),
                            ("Class D", "Class D"),
                            ("Class F", "Class F"),
                            ("Electrical Fires", "Electrical Fires"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "certification",
                    models.CharField(
                        choices=[
                            ("CE Marking", "CE Marking"),
                            ("UL", "UL"),
                            ("FM", "FM"),
                            ("BSI Kitemark", "BSI Kitemark"),
                            ("EN3", "EN3"),
                            ("DIN", "DIN"),
                            ("NFPA", "NFPA"),
                            ("AS", "AS"),
                            ("ISI Mark", "ISI Mark"),
                            ("TUV", "TUV"),
                            ("ISO", "ISO"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "standards_compliance",
                    models.CharField(
                        choices=[
                            ("EN3", "EN3"),
                            ("ISO_9001", "ISO_9001"),
                            ("NFPA_10", "NFPA_10"),
                            ("NFPA_17", "NFPA_17"),
                            ("BS EN_1866", "BS EN_1866"),
                            ("ANSI UL_299", "ANSI UL_299"),
                            ("ISO_11602", "ISO_11602"),
                            ("AS_2444", "AS_2444"),
                            ("JIS", "JIS"),
                            ("CCC", "CCC"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("inspection_date", models.DateField()),
                ("service_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("manufacture_date", models.DateField()),
                ("inventory", models.PositiveIntegerField()),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "warranty_period",
                    models.PositiveIntegerField(help_text="Warranty period in months"),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_images/"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address",
                        to="app.address",
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_address",
                        to="app.address",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_address",
                        to="app.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fire_extinguisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.fireextinguisher",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("System User", "System User"),
                            ("Company Admin", "Company Admin"),
                            ("System Admin", "System Admin"),
                        ],
                        default="User",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="app.company",
                    ),
                ),
            ],
        ),
    ]
