# Generated by Django 5.1.2 on 2024-12-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_company_name_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="user_signature/"),
        ),
    ]
